# Menu config

[[main]]
  identifier = "docs"
  pre = ""
  post = ""
  name = "Docs"
  url = "/categories/docs/"
  title = ""
  weight = 1
[[main]]
  identifier = "tags"
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""
  weight = 3
[[main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "Categories"
  url = "/categories/"
  title = ""
  weight = 4
[[main]]
  identifier = "github"
  pre = "<i class='fab fa-github fa-fw'></i>"
  post = ""
  name = ""
  url = "https://github.com/HEIGE-PCloud/DoIt"
  title = "GitHub"
  weight = 5